name: Deploy to GKE

# Triggers the workflow on push events to the main branch
on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to GKE
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Authenticate to Google Cloud
      id: auth
      uses: google-github-actions/auth@v2
      with:
        workload_identity_provider: 'projects/831227581465/locations/global/workloadIdentityPools/n8n-github-pool-v2/providers/github-provider'
        service_account: 'github-actions-runner@celtic-facility-474000-j0.iam.gserviceaccount.com'

    - name: Get GKE credentials
      uses: google-github-actions/get-gke-credentials@v1
      with:
        cluster_name: 'n8n-cluster'
        location: 'us-central1'

    - name: Deploy to GKE
      run: |-
        kubectl apply -f n8n-deployment.yaml